### ISSUE TITLE
AttributeError: '<CompositeObject>' object has no attribute 'IsPaused'

### ISSUE THREAD

**Issue by joepvd** [kdani3/i3-gnome-pomodoro#6] opened 2017-07-12 09:56 UTC
```
% python pomodoro-client.py status
...
  File "pomodoro-client.py", line 79, in status
    pomodoro_data = extract_pomodoro_data(pomodoro)
  File "pomodoro-client.py", line 45, in extract_pomodoro_data
    "elapsed": pomodoro.Elapsed, "is_paused": pomodoro.IsPaused,
AttributeError: '<CompositeObject>' object has no attribute 'IsPaused'

% python --version 
Python 2.7.12
```

On Ubuntu 16.04 LTS

**Comment by kantord** [comment] 2017-07-19 14:32
Do you have gnome-pomodoro installed? (http://gnomepomodoro.org/) If so, which version?

**Comment by chikh** [comment] 2017-08-04 12:39
@kantord The same issue here. Ubuntu 16.04, gnome-shell-pomodoro package version is 0.11.0-2build1. Also if I put:
```python
def extract_pomodoro_data(pomodoro):
    print [method for method in dir(pomodoro) if callable(getattr(pomodoro, method))]
    return {
        "elapsed": pomodoro.Elapsed, "is_paused": pomodoro.IsPaused,
        "duration": pomodoro.StateDuration,
        "remaining": pomodoro.StateDuration - pomodoro.Elapsed,
        "state": pomodoro.State
    }
```
I have the output:
```python
['Activate', 'ActivateAction', 'Changed', 'CommandLine', 'Describe', 'DescribeAll', 'Get', 'GetAll', 'GetMachineId', 'Introspect', 'List', 'NotifyPomodoroEnd', 'NotifyPomodoroStart', 'Open', 'Ping', 'PropertiesChanged', 'Reset', 'Set', 'SetState', 'ShowPreferences', 'Start', 'Stop', '_Introspect', '__class__', '__delattr__', '__format__', '__getattribute__', '__getitem__', '__hash__', '__init__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__']

Traceback (most recent call last):
  File "./pomodoro-client.py", line 222, in <module>
    main()
  File "/home/chikh/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/chikh/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/chikh/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/chikh/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/chikh/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "./pomodoro-client.py", line 80, in status
    pomodoro_data = extract_pomodoro_data(pomodoro)
  File "./pomodoro-client.py", line 46, in extract_pomodoro_data
    "elapsed": pomodoro.Elapsed, "is_paused": pomodoro.IsPaused,
AttributeError: '<CompositeObject>' object has no attribute 'IsPaused'
```
So really no `IsPaused` function there. Hope it helps.

**Comment by kantord** [comment] 2017-08-05 14:58
Version 0.11.0 is very outdated. In fact, that was released in 2015.

I checked and indeed, `IsPaused` is nowhere to be found in any of v. 0.11.0's source files.

This repo is basically a drafted script, not a stable software. Maybe I'm the only one to actively use it currently. Therefore, I don't intend to support Ubuntu 16.04, or any distro with such ancient packages, because it's not worth it to create a workaround for `IsPaused`, if it's even possible.

To the rescue, you have your PPA: http://www.webupd8.org/2017/02/gnome-pomodoro-pomodoro-timer-with.html I trust it should have a version that is up-to-date enough to have `IsPaused`. If that doesn't work out, your next easiest solution is installing from source.

If you are interested and have a better-than-a-workaround solution in mind to support Ubuntu 16.04, any collaboration is welcome!

As this issue is almost certainly caused by your version of gnome-pomodoro not having such feature, I'm closing this issue. If after installing the latest release the same issue still comes up, feel free to re-open.

**Closed as completed by kantord** 2017-08-05 14:58 UTC

**Comment by chikh** [comment] 2017-08-07 08:54
Thanks, @kantord ! Everything works just fine now. Also I've found more options to get a newer version right from the official site: http://gnomepomodoro.org/
